apiVersion: v2
name: cbt
description: A simple ClickHouse-focused data transformation tool
home: https://github.com/ethpandaops/cbt
type: application
version: 0.0.1
maintainers:
  - name: savid
    email: andrew.davis@ethereum.org
