image:
  repository: ethpandaops/panda-pulse
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  grafanaBaseUrl: ""  # optional
  prometheusDatasourceId: ""  # optional
  healthCheckAddress: ""  # optional
  metricsAddress: ""  # optional
  s3:
    bucket: "YOUR_S3_BUCKET"  # required
    bucketPrefix: ""  # optional, defaults to "ethrand"
    region: "ams3"  # optional, defaults to ams3
    endpointUrl: ""  # optional

secrets:
  grafanaServiceToken: "YOUR_GRAFANA_SERVICE_TOKEN"  # required
  discordBotToken: "YOUR_DISCORD_BOT_TOKEN"  # required
  s3AccessKeyId: "YOUR_S3_ACCESS_KEY_ID"  # required
  s3SecretAccessKey: "YOUR_S3_SECRET_ACCESS_KEY"  # required

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

nodeSelector: {}
tolerations: []
affinity: {}
