apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse-movoor.fullname" . }}
  labels:
    {{- include "clickhouse-movoor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "clickhouse-movoor.metricsPort" . }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if (include "clickhouse-movoor.probePort" .) }}
    - port: {{ include "clickhouse-movoor.probePort" . }}
      targetPort: probe
      protocol: TCP
      name: probe
    {{- end }}
    {{- if (include "clickhouse-movoor.frontendPort" .) }}
    - port: {{ include "clickhouse-movoor.frontendPort" . }}
      targetPort: frontend
      protocol: TCP
      name: frontend
    {{- end }}
  {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 4}}
  {{- end }}
  selector:
    {{- include "clickhouse-movoor.selectorLabels" . | nindent 4 }}
