apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cbt.fullname" . }}
  labels:
    {{- include "cbt.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ toYaml .Values.config | nindent 4 }}
