apiVersion: v1
kind: Service
metadata:
  name: {{ include "cbt.fullname" . }}
  labels:
    {{- include "cbt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "cbt.metricsPort" . }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if (include "cbt.pprofPort" .) }}
    - port: {{ include "cbt.pprofPort" . }}
      targetPort: pprof
      protocol: TCP
      name: pprof
    {{- end }}
    {{- if (include "cbt.probePort" .) }}
    - port: {{ include "cbt.probePort" . }}
      targetPort: probe
      protocol: TCP
      name: probe
    {{- end }}
  {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 4}}
  {{- end }}
  selector:
    {{- include "cbt.selectorLabels" . | nindent 4 }}
