{{- if eq (.Values.kind | default "Deployment") "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wagie.fullname" . }}
  labels:
    {{- include "wagie.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not (kindIs "invalid" .Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wagie.selectorLabels" . | nindent 6 }}
  template:
    {{- include "wagie.podSpec" . | nindent 4 }}
{{- end }}
