apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panda-pulse.fullname" . }}
  labels:
    {{- include "panda-pulse.labels" . | nindent 4 }}
type: Opaque
data:
  grafana-service-token: {{ required "A valid Grafana service token is required" .Values.secrets.grafanaServiceToken | b64enc }}
  discord-bot-token: {{ required "A valid Discord bot token is required" .Values.secrets.discordBotToken | b64enc }}
  {{- if .Values.secrets.openrouterApiKey }}
  openrouter-api-key: {{ .Values.secrets.openrouterApiKey | b64enc }}
  {{- end }} 