apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "asynqmon.fullname" . }}
  labels:
    {{- include "asynqmon.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "asynqmon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "asynqmon.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "asynqmon.serviceAccountName" . }}
    {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      initContainers:
      {{- if .Values.initContainers }}
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        {{- if gt (len .Values.customCommand) 0 }}
          {{- toYaml .Values.customCommand | nindent 12}}
        {{- else }}
          - /asynqmon
          {{- if gt (len .Values.args) 0 }}
          {{- toYaml .Values.args | nindent 12}}
          {{- end }}
        {{- end }}
        {{- if gt (len .Values.customArgs) 0 }}
        args:
          {{- toYaml .Values.customArgs | nindent 12}}
        {{- end }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 12 }}
        volumeMounts:
          {{- if .Values.extraVolumeMounts }}
            {{ toYaml .Values.extraVolumeMounts | nindent 10 }}
          {{- end }}
        ports:
          - name: http
            containerPort: {{ include "asynqmon.httpPort" . }}
            protocol: TCP
          {{- if .Values.extraPodPorts }}
            {{ toYaml .Values.extraPodPorts | nindent 10 }}
          {{- end }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        lifecycle:
          {{- toYaml .Values.lifecycle | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
          - name: PORT
            value: {{ .Values.config.port | quote }}
          {{- if .Values.config.redis.url }}
          - name: REDIS_URL
            value: {{ .Values.config.redis.url | quote }}
          {{- end }}
          {{- if .Values.config.redis.addr }}
          - name: REDIS_ADDR
            value: {{ .Values.config.redis.addr | quote }}
          {{- end }}
          - name: REDIS_DB
            value: {{ .Values.config.redis.db | quote }}
          {{- if .Values.config.redis.password }}
          - name: REDIS_PASSWORD
            value: {{ .Values.config.redis.password | quote }}
          {{- end }}
          {{- if .Values.config.redis.clusterNodes }}
          - name: REDIS_CLUSTER_NODES
            value: {{ .Values.config.redis.clusterNodes | quote }}
          {{- end }}
          {{- if .Values.config.redis.tls }}
          - name: REDIS_TLS
            value: {{ .Values.config.redis.tls | quote }}
          {{- end }}
          - name: REDIS_INSECURE_TLS
            value: {{ .Values.config.redis.insecureTLS | quote }}
          - name: ENABLE_METRICS_EXPORTER
            value: {{ .Values.config.metrics.enabled | quote }}
          {{- if .Values.config.metrics.prometheusAddr }}
          - name: PROMETHEUS_ADDR
            value: {{ .Values.config.metrics.prometheusAddr | quote }}
          {{- end }}
          - name: READ_ONLY
            value: {{ .Values.config.readOnly | quote }}
        {{- range $key, $value := .Values.secretEnv }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ include "asynqmon.fullname" $ }}-env
                key: {{ $key }}
        {{- end }}
        {{- if .Values.extraEnv }}
          {{- toYaml .Values.extraEnv | nindent 12 }}
        {{- end }}
      {{- if .Values.extraContainers }}
        {{ toYaml .Values.extraContainers | nindent 8}}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
      {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8}}
      {{- end }}
