apiVersion: v1
kind: Service
metadata:
  name: {{ include "asynqmon.fullname" . }}
  labels:
    {{- include "asynqmon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "asynqmon.httpPort" . }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 4}}
  {{- end }}
  selector:
    {{- include "asynqmon.selectorLabels" . | nindent 4 }}
