target: all

config:
  data-dir: /data

  database:
    type: sqlite
    dsn: "file:/data/wagie.db"

  headquarters:
    http-listen-address: ":8080"

  worker:
    name: "worker"

  leadership:
    name: "leadership"

  assistant:
    name: "assistant"

  web:
    http-listen-address: ":8080"
